# Generated by Django 6.0.6 on 2026-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='industry')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('brand_colors', models.JSONField(blank=True, default=list, verbose_name='brand colors')),
                ('logo', models.CharField(blank=True, max_length=512, verbose_name='logo object path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
