/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth-token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["companies_list"];
        put?: never;
        post: operations["companies_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_pk}/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["companies_documents_list"];
        put?: never;
        post: operations["companies_documents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_pk}/documents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["companies_documents_retrieve"];
        put?: never;
        post?: never;
        delete: operations["companies_documents_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_pk}/documents/{id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["companies_documents_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_pk}/documents/{id}/view-url/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Signed GET URL so the browser can open the stored PDF (spec §5.3). */
        get: operations["companies_documents_view_url_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["companies_retrieve"];
        put: operations["companies_update"];
        post?: never;
        delete: operations["companies_destroy"];
        options?: never;
        head?: never;
        patch: operations["companies_partial_update"];
        trace?: never;
    };
    "/api/companies/logo-upload-url/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["companies_logo_upload_url_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Aggregate counts powering the dashboard's stat cards. */
        get: operations["dashboard_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["materials_list"];
        put?: never;
        post: operations["materials_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["materials_retrieve"];
        put: operations["materials_update"];
        post?: never;
        delete: operations["materials_destroy"];
        options?: never;
        head?: never;
        patch: operations["materials_partial_update"];
        trace?: never;
    };
    "/api/materials/{id}/regenerate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["materials_regenerate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Templates are create-only in MVP: no update/delete (spec §5.1). */
        get: operations["templates_list"];
        put?: never;
        /** @description Templates are create-only in MVP: no update/delete (spec §5.1). */
        post: operations["templates_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Templates are create-only in MVP: no update/delete (spec §5.1). */
        get: operations["templates_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_retrieve"];
        put: operations["users_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["users_partial_update"];
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthToken: {
            username: string;
            password: string;
            readonly token: string;
        };
        Company: {
            readonly id: number;
            name: string;
            website?: string;
            industry?: string;
            description?: string;
            brand_colors?: string[];
            /** Logo object path */
            logo?: string;
            readonly logo_url: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly last_updated: string;
        };
        CompanySummary: {
            readonly id: number;
            name: string;
            readonly logo_url: string | null;
        };
        /** @description Read-only aggregate counts for the dashboard stat cards. */
        DashboardStats: {
            companies_count: number;
            documents_processed: number;
            documents_processing: number;
            materials_generated: number;
            materials_needs_review: number;
        };
        Document: {
            readonly id: number;
            readonly company: number;
            file_name: string;
            content_type: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly page_count: number | null;
            readonly chunks_count: number;
            readonly tables_count: number;
            readonly images_count: number;
            readonly error_message: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        DocumentCreateRequest: {
            file_name: string;
            content_type: string;
        };
        DocumentCreateResponse: {
            id: number;
            company: number;
            file_name: string;
            content_type: string;
            status: string;
            page_count: number | null;
            chunks_count: number;
            tables_count: number;
            images_count: number;
            error_message: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uri */
            upload_url: string;
        };
        DocumentViewUrl: {
            /** Format: uri */
            url: string;
        };
        GenerationSource: {
            readonly id: number;
            source_role: components["schemas"]["SourceRoleEnum"];
            page_number?: number | null;
            snippet?: string;
            used_fact?: string;
            /** Format: double */
            relevance_score?: number | null;
            readonly document: components["schemas"]["SourceDocument"];
        };
        /**
         * @description * `queued` - Queued
         *     * `processing` - Processing
         *     * `completed` - Completed
         *     * `failed` - Failed
         * @enum {string}
         */
        GenerationStatusEnum: "queued" | "processing" | "completed" | "failed";
        LogoUploadUrl: {
            /** Format: uri */
            upload_url: string;
            object_path: string;
        };
        LogoUploadUrlRequest: {
            filename: string;
            content_type: string;
        };
        MaterialCreate: {
            readonly id: number;
            title: string;
            description?: string;
            sender_company: number;
            receiver_company: number;
            template: number;
            prompt: string;
            tone?: string;
            cta_style?: string;
            cta_link?: string;
            language?: string;
        };
        MaterialDetail: {
            readonly id: number;
            title: string;
            readonly sender_company: components["schemas"]["CompanySummary"];
            readonly receiver_company: components["schemas"]["CompanySummary"];
            readonly template_slug: string;
            generation_status?: components["schemas"]["GenerationStatusEnum"];
            review_status?: components["schemas"]["ReviewStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            description?: string;
            prompt: string;
            tone?: string;
            cta_style?: string;
            cta_link?: string;
            language?: string;
            readonly template: components["schemas"]["Template"];
            output_json?: unknown;
            validation_result?: unknown;
            error_message?: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly sources: components["schemas"]["GenerationSource"][];
        };
        MaterialList: {
            readonly id: number;
            title: string;
            readonly sender_company: components["schemas"]["CompanySummary"];
            readonly receiver_company: components["schemas"]["CompanySummary"];
            readonly template_slug: string;
            generation_status?: components["schemas"]["GenerationStatusEnum"];
            review_status?: components["schemas"]["ReviewStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        /**
         * @description Body for the ``regenerate`` action.
         *
         *     ``prompt`` is optional: omit it to re-run with the stored prompt, or pass a
         *     new one to edit-and-regenerate in a single request (no separate PATCH).
         */
        MaterialRegenerate: {
            prompt?: string;
        };
        MaterialUpdate: {
            readonly id: number;
            title: string;
            description?: string;
            prompt: string;
            cta_link?: string;
            review_status?: components["schemas"]["ReviewStatusEnum"];
        };
        PatchedCompany: {
            readonly id?: number;
            name?: string;
            website?: string;
            industry?: string;
            description?: string;
            brand_colors?: string[];
            /** Logo object path */
            logo?: string;
            readonly logo_url?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly last_updated?: string;
        };
        PatchedMaterialUpdate: {
            readonly id?: number;
            title?: string;
            description?: string;
            prompt?: string;
            cta_link?: string;
            review_status?: components["schemas"]["ReviewStatusEnum"];
        };
        PatchedUser: {
            /** Name of User */
            name?: string;
            /** Format: uri */
            readonly url?: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `approved` - Approved
         *     * `rejected` - Rejected
         * @enum {string}
         */
        ReviewStatusEnum: "pending" | "approved" | "rejected";
        SourceDocument: {
            readonly id: number;
            file_name: string;
            company: number;
        };
        /**
         * @description * `sender` - Sender
         *     * `receiver` - Receiver
         * @enum {string}
         */
        SourceRoleEnum: "sender" | "receiver";
        /**
         * @description * `pending` - Pending
         *     * `processing` - Processing
         *     * `processed` - Processed
         *     * `failed` - Failed
         * @enum {string}
         */
        StatusEnum: "pending" | "processing" | "processed" | "failed";
        Template: {
            readonly id: number;
            name: string;
            readonly slug: string;
            description?: string;
            constraints?: unknown;
            image_slots?: unknown;
            theme?: unknown;
            readonly is_active: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        User: {
            /** Name of User */
            name?: string;
            /** Format: uri */
            readonly url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AuthToken"];
                "multipart/form-data": components["schemas"]["AuthToken"];
                "application/json": components["schemas"]["AuthToken"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"];
                };
            };
        };
    };
    companies_list: {
        parameters: {
            query?: {
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"][];
                };
            };
        };
    };
    companies_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Company"];
                "application/x-www-form-urlencoded": components["schemas"]["Company"];
                "multipart/form-data": components["schemas"]["Company"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    companies_documents_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
        };
    };
    companies_documents_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DocumentCreateRequest"];
                "multipart/form-data": components["schemas"]["DocumentCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentCreateResponse"];
                };
            };
        };
    };
    companies_documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_pk: number;
                /** @description A unique integer value identifying this document. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    companies_documents_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_pk: number;
                /** @description A unique integer value identifying this document. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_documents_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_pk: number;
                /** @description A unique integer value identifying this document. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    companies_documents_view_url_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_pk: number;
                /** @description A unique integer value identifying this document. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentViewUrl"];
                };
            };
        };
    };
    companies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this company. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    companies_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this company. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Company"];
                "application/x-www-form-urlencoded": components["schemas"]["Company"];
                "multipart/form-data": components["schemas"]["Company"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    companies_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this company. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this company. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCompany"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCompany"];
                "multipart/form-data": components["schemas"]["PatchedCompany"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    companies_logo_upload_url_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoUploadUrlRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoUploadUrlRequest"];
                "multipart/form-data": components["schemas"]["LogoUploadUrlRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoUploadUrl"];
                };
            };
        };
    };
    dashboard_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    materials_list: {
        parameters: {
            query?: {
                /** @description Sender OR receiver company id */
                company?: number;
                generation_status?: string;
                receiver?: number;
                review_status?: string;
                /** @description A search term. */
                search?: string;
                sender?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialList"][];
                };
            };
        };
    };
    materials_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["MaterialCreate"];
                "multipart/form-data": components["schemas"]["MaterialCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDetail"];
                };
            };
        };
    };
    materials_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this marketing material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDetail"];
                };
            };
        };
    };
    materials_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this marketing material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["MaterialUpdate"];
                "multipart/form-data": components["schemas"]["MaterialUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialUpdate"];
                };
            };
        };
    };
    materials_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this marketing material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    materials_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this marketing material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMaterialUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMaterialUpdate"];
                "multipart/form-data": components["schemas"]["PatchedMaterialUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialUpdate"];
                };
            };
        };
    };
    materials_regenerate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this marketing material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MaterialRegenerate"];
                "application/x-www-form-urlencoded": components["schemas"]["MaterialRegenerate"];
                "multipart/form-data": components["schemas"]["MaterialRegenerate"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDetail"];
                };
            };
            /** @description Generation already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    templates_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"][];
                };
            };
        };
    };
    templates_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Template"];
                "application/x-www-form-urlencoded": components["schemas"]["Template"];
                "multipart/form-data": components["schemas"]["Template"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
        };
    };
    templates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this template. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
