# Generated by Django 6.0.6 on 2026-07-07 17:06

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

# pgvector==0.4.1's VectorExtension.__init__ does not call
# CreateExtension.__init__, so `self.hints` is never set. Django 6.0's
# CreateExtension.database_forwards/backwards reads `self.hints`, which
# raises AttributeError. Patch it in until pgvector ships a fixed release.
_vector_extension = VectorExtension()
_vector_extension.hints = {}


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        _vector_extension,
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(max_length=32, verbose_name='chunk type')),
                ('page_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='companies.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'verbose_name': 'document chunk',
                'verbose_name_plural': 'document chunks',
                'ordering': ['document_id', 'page_number', 'id'],
            },
        ),
    ]
