# Generated by Django 6.0.6 on 2026-07-14 13:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documentchunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
