# Generated by Django 6.0.6 on 2026-07-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0002_documentchunk'),
        ('materials', '0002_seed_default_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('prompt', models.TextField(verbose_name='prompt')),
                ('tone', models.CharField(default='professional', max_length=32, verbose_name='tone')),
                ('cta_style', models.CharField(default='soft', max_length=32, verbose_name='cta style')),
                ('language', models.CharField(default='english', max_length=32, verbose_name='language')),
                ('generation_status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16, verbose_name='generation status')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16, verbose_name='review status')),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('validation_result', models.JSONField(blank=True, null=True)),
                ('retrieved_context', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('job_operation_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_as_receiver', to='companies.company')),
                ('sender_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_as_sender', to='companies.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.template')),
            ],
            options={
                'verbose_name': 'marketing material',
                'verbose_name_plural': 'marketing materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_role', models.CharField(choices=[('sender', 'Sender'), ('receiver', 'Receiver')], max_length=16)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True)),
                ('used_fact', models.CharField(blank=True, max_length=1000)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_sources', to='documents.documentchunk')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_sources', to='companies.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_sources', to='documents.document')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='materials.marketingmaterial')),
            ],
            options={
                'verbose_name': 'generation source',
                'verbose_name_plural': 'generation sources',
                'ordering': ['material_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='marketingmaterial',
            index=models.Index(fields=['generation_status'], name='materials_m_generat_f08fc5_idx'),
        ),
    ]
