# Generated by Django 6.0.6 on 2026-07-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_marketingmaterial_generationsource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingmaterial",
            name="cta_link",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="cta link"
            ),
        ),
    ]
